# Generated by Django 4.1.3 on 2022-12-14 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('profileImage', models.ImageField(blank=True, default='../static/images/defaultImage.svg', null=True, upload_to='')),
                ('dOB', models.DateField(blank=True, null=True)),
                ('phoneNumber', models.IntegerField(blank=True, null=True)),
                ('addressLine1', models.CharField(blank=True, max_length=200)),
                ('addressLine2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_tag', models.CharField(choices=[('SP', 'Sports'), ('TECH', 'Technology'), ('CLTH', 'Clothes'), ('KIT', 'Kitchen'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('description', models.TextField()),
                ('startingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pictureOfItem', models.ImageField(upload_to='')),
                ('startDateTimeItem', models.DateTimeField()),
                ('endDateTimeItem', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.TextField()),
                ('dateTimeOfQuestion', models.DateTimeField()),
                ('itemFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.item')),
                ('userFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateTimeBids', models.DateTimeField()),
                ('itemIDFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.item')),
                ('userIDFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerText', models.TextField()),
                ('dateTimeOfAnswer', models.DateTimeField()),
                ('questionFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.question')),
            ],
        ),
    ]
